/**
 * Valid vCard property names.
 *
 * @category Properties
 * @see https://datatracker.ietf.org/doc/html/rfc6350#section-10.3.1
 */
export enum PropertyName {
  address = "ADR",
  anniversary = "ANNIVERSARY",
  begin = "BEGIN",
  birthday = "BDAY",
  calendarAddressUri = "CALADRURI",
  calendarUri = "CALURI",
  categories = "CATEGORIES",
  clientPidMap = "CLIENTPIDMAP",
  email = "EMAIL",
  end = "END",
  fbUrl = "FBURL",
  fullName = "FN",
  gender = "GENDER",
  geoLocation = "GEO",
  impp = "IMPP",
  key = "KEY",
  kind = "KIND",
  language = "LANG",
  logo = "LOGO",
  member = "MEMBER",
  name = "N",
  nickName = "NICKNAME",
  note = "NOTE",
  organization = "ORG",
  photo = "PHOTO",
  productId = "PRODID",
  related = "RELATED",
  revision = "REV",
  role = "ROLE",
  sound = "SOUND",
  source = "SOURCE",
  tel = "TEL",
  timezone = "TZ",
  title = "TITLE",
  uid = "UID",
  url = "URL",
  version = "VERSION",
  xml = "XML",
}
