name: Build and Test

on: [pull_request]

jobs:
  test:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build